name = "nuxt-convex-playground"
main = "dist/_worker.js/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true
head_sampling_rate = 1

# Cron trigger - daily at 3am UTC
[triggers]
crons = [ "0 3 * * *" ]
