name = "nuxt-convex-playground"
main = "dist/_worker.js/index.js"
compatibility_date = "2025-01-01"

[observability]
enabled = true

# Cron trigger - daily at 3am UTC
[triggers]
crons = ["0 3 * * *"]
